spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/energydb
    username: disysuser
    password: disyspw

  flyway:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: info
